version: '2.0'
### Local setup ###
services:
    testscrape:
        build:
            context: ./
        container_name: testscrape
        ports:
            - "799:10001"
        volumes:
         - ../:/var/www
         - /var/www/docker


